### PR TITLE
Added support for Air-Gap installations

### PR DESCRIPTION
**Pull request by bdun1013**
## Description

Air-Gap installation support was added following the documentation at https://rancher.com/docs/k3s/latest/en/installation/airgap/

Five flags were added to both the `install` and `join` commands:

- airgap (bool: Perform an airgap install)
- k3s-binary (string: Path to the k3s binary)
- install-script (string: Path to the k3s install script)
- airgap-images-archive (string: Path to the k3s airgap images archive)
- registries-config (string: Path to the k3s registries configuration file)

When the `airgap` flag is set, `k3s-binary` and `install-script` are required, and `airgap-images-archive` OR  `registries-config` is required.

The k3s binary, k3s installation script, and airgap images archive and/or registries config file is copied to the remote target node using https://github.com/pkg/sftp. The k3s install script is then run with `INSTALL_K3S_SKIP_DOWNLOAD=true` to prevent the script from trying to download the k3s binary and the installation runs as normal.

## Motivation and Context

- [x] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

This PR will address:
- https://github.com/alexellis/k3sup/issues/301
- https://github.com/alexellis/k3sup/issues/26
- https://github.com/alexellis/k3sup/issues/221

`k3sup` currently does not support https://rancher.com/docs/k3s/latest/en/installation/airgap/. I, along with others, would like to use k3sup to provision k3s clusters in Air-Gap environments. 

## How Has This Been Tested?

I have tested the updates to the `install` and `join` commands on a Raspberry Pi 4 cluster. I verified that the `INSTALL_K3S_SKIP_DOWNLOAD` flag is passed to the installation script on both commands and that the cluster is provisioned correctly.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by bdun1013** [comment]
For my use case, I will probably build a Docker image that contains [k3sup](https://github.com/alexellis/k3sup/releases/download/0.11.1/k3sup), [k3s](https://github.com/k3s-io/k3s/releases/download/v1.21.4-engine0%2Bk3s1/k3s), [install.sh](https://get.k3s.io/), and [k3s-airgap-images-amd64.tar.zst](https://github.com/k3s-io/k3s/releases/download/v1.21.4-engine0%2Bk3s1/k3s-airgap-images-arm.tar.zst). I will then transfer this image to my Air-Gap environment and use it for k3s cluster installation.

**Comment by cchanley2003** [comment]
I'll be curious the response to this PR. We were looking into doing airgap installation as well, but my approach is different. 

Mostly to remove the hard coded k3s install script url. I believe the install script supports custom url locations for its artifacts. So if you can host the scripts and the artifacts behind a webserver/minio bucket in your air gapped situation then I believe that should work.

In the process of testing that out now, but wanted to get the thought out there.

**Comment by YAMLcase** [comment]
@cchanley2003 Did you have any luck with your airgapped solution?

**Comment by cchanley2003** [comment]
We did.  It did require some changes. It was to remove the hard coded k3s url (move it to a command line argument that defaults to get.k3s.io) and also add command line argument to support additional env variables to be handed to the script.  Debating whether to submit open an issue/submit a PR.

**Comment by YAMLcase** [comment]
> We did.  It did require some changes. It was to remove the hard coded k3s url (move it to a command line argument that defaults to get.k3s.io) and also add command line argument to support additional env variables to be handed to the script.  Debating whether to submit open an issue/submit a PR.

Oh wow.  If you already have it in a fork, would you mind sharing that with me?

**Comment by alexellis** [comment]
Thanks for your interest, but all enhancements and features must be proposed and agreed upon within an Issue before they are worked on.

**Pull request closed without merging**
