### PR TITLE
Fixes #228 support downloading into a folder with a space

### LINKED ISSUE #228: "Could not resolve host" when running install script on Mac
## Expected Behaviour
Running `curl -sLS https://get.k3sup.dev | sh` should tolerate directories with spaces in them. On my Mac, since I use a Personal and Business Dropbox I have `/Users/me/Dropbox (Business)` and `/Users/me/Dropbox (Personal)`. 

## Current Behaviour
Currently, installation script errors out with:
```
sh: line 101: [: /Users/wk/Dropbox: binary operator expected
Downloading package https://github.com/alexellis/k3sup/releases/download/0.9.2/k3sup-darwin as /Users/wk/Dropbox (Personal)/projects/personal/k3sup-darwin
curl: (23) Failed writing body (0 != 16360)
curl: (6) Could not resolve host: (Personal)
```

## Possible Solution
Add handling for directories with spaces. 

## Steps to Reproduce (for bugs)

1. Run `curl -sLS https://get.k3sup.dev | sh` on Mac where there is a space in the target directory name.

## Context
Attempting to install on MacOS. Easy workaround by using a different directory without space in the name.

## Your Environment
Raspberry Pi 4's on Raspbian
MacOS 10.15.3

### PR DESCRIPTION
**Pull request by Amalkh5**
This commit will solve issue #228 which will add support for downloading into a folder with space.

Signed-off-by: Amal Alkhamees <amalkms5@gmail.com>

## Motivation and Context

- [ ] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

## How Has This Been Tested?

```
$ pwd
/Users/amal/go/src/github.com/k3sup/test k3sup
$ ../get.sh
Downloading package https://github.com/alexellis/k3sup/releases/download/0.9.2/k3sup-darwin as /Users/amal/go/src/github.com/k3sup/test k3sup/k3sup-darwin
Download complete.

Running with sufficient permissions to attempt to move k3sup to /usr/local/bin
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
../get.sh: line 161: [: /Users/amal/go/src/github.com/k3sup/test: binary operator expected
 _    _____                 
| | _|___ / ___ _   _ _ __  
| |/ / |_ \/ __| | | | '_ \ 
|   < ___) \__ \ |_| | |_) |
|_|\_\____/|___/\__,_| .__/ 
                     |_|    
Version: 0.9.2

```

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
Hi @Amalkh5 thanks for raising the PR.

I need a bit more context in the section `How Has This Been Tested?` - all I see is error messages and that doesn't given me confidence to merge this.

How about writing about what you're showing us?

Alex

**Comment by Amalkh5** [comment]
Hi @alexellis ,
there was an issue with line 161 with spaces, I fixed it. 

here is the test after the fix:- 
1. Created the folder with spaces in the name.
2.  Cd into the folder


```
➜ k3sup git:(issue-228) ✗ pwd
/Users/amal/go/src/github.com/k3sup/test k3sup
```
3.  Run the  Script.
```
➜  k3sup git:(issue-228) ✗ sh ../get.sh   
Downloading package https://github.com/alexellis/k3sup/releases/download/0.9.2/k3sup-darwin as /Users/amal/go/src/github.com/k3sup/test k3sup/k3sup-darwin
Download complete.

Running with sufficient permissions to attempt to move k3sup to /usr/local/bin
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
 _    _____                 
| | _|___ / ___ _   _ _ __  
| |/ / |_ \/ __| | | | '_ \ 
|   < ___) \__ \ |_| | |_) |
|_|\_\____/|___/\__,_| .__/ 
                     |_|    
Version: 0.9.2
Git Commit: 5a636dba10e1f8e6bb4bb5982c6e04fc21c34534 ```

**Comment by alexellis** [comment]
Thank you, this looks to be as expected.

**Comment by alexellis** [comment]
This can be replicated to arkade, inlets, inletsctl, faas-cli and any other projects we are maintaining in the community.

**Pull request merged**
