### PR TITLE
Always download the binary with k3sup name in get.sh

### LINKED ISSUE #46: Following the installation scripts fails
## Expected Behaviour
Copy and paste the commands from the Installation instructions in `README.md` would work.

## Current Behaviour
The first line from the installation instructions gives me the `k3sup-$arch` binary and correct instructions:
```bash
$ curl -sLS https://get.k3sup.dev | sh
=========================================================
==    As the script was run as a non-root user the     ==
==    following commands may need to be run manually   ==
=========================================================

  sudo cp k3sup-darwin /usr/local/bin/k3sup
```

But the second command in the instructions fails, because the binary name is different:
```bash
$ sudo install k3sup /usr/local/bin/
install: k3sup: No such file or directory
```

## Possible Solution
1. Remove second line of installation, letting the user follow the instructions from the `get.sh` output
2. After downloading the binary, rename it from `k3sup-$arch` to `k3sup` and adjust the instructions in the `get.sh` output to `sudo cp k3sup /usr/local/bin/k3sup`

## Steps to Reproduce (for bugs)
1. Execute exactly the installation instructions

## Context
A quick change to yield a better experience when installing the binary. The first impression sticks 😅

## Your Environment
- MacOS.

### PR DESCRIPTION
**Pull request by jonatasbaldin**
Signed-off-by: Jonatas Baldin <jonatas.baldin@gmail.com>

## Description
Fix #46.

## Motivation and Context

- [x] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

## How Has This Been Tested?
By executing the exactly installation instruction from the README.md.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
@rgee0 PTAL?

**Comment by rgee0** [comment]
If this is going in I could do with it happening before I change the root user test to fix #58

**Comment by alexellis** [comment]
OK I'll get it merged, thanks @jonatasbaldin

**Comment by rgee0** [comment]
This was in place to enable verifying checksums of each of the binaries.  Whilst not implemented on this repo yet it is where this script originated from.

**Comment by alexellis** [comment]
OK so what happens now where this change may be duplicated? We may need to run the checksum on the generated name vs the downloaded name?

**Comment by rgee0** [comment]
The original name is included in the .sha file so the checksum fails as the generic name doesnt match the suffixed name included in the file

**Pull request merged**
