### PR TITLE
Migrate to GitHub actions and go modules

### PR DESCRIPTION
**Pull request by thomaspeitz**
Hey Alex,

as discussed a small PR to migrate to github actions.

I migrated to golang modules as well as it makes the release process a lot easier (no more gopath needed)

See https://github.com/thomaspeitz/k3sup/releases/tag/0.3.8 for an example of a release.

Greetings, Thomas

### CODE REVIEW

**Comment by thomaspeitz** [comment]
```git filter-branch --msg-filter 'cat - && echo && echo "Signed-off-by: Thomas Peitz <thomas.peitz@nerdswords.de>" "$@";' HEAD~8..HEAD``` - Github easy as always :D

**Comment by alexellis** [comment]
Hi @thomaspeitz there's been a few changes since your PR, could you rebase / re-test? Thanks

Alex

**Comment by thomaspeitz** [comment]
Hey Alex :), updated branch. Will verify that everything still works and tag you afterwards.

**Comment by alexellis** [comment]
Hi, I've made the migration to modules now and CI is still working out OK for the time being. I need to take another look at your PR though.

**Comment by thomaspeitz** [comment]
Just ping me if i can help to get this merged :) Greetings :))

**Comment by alexellis** [comment]
Sorry for the delay on this, I think we'll stick with Travis for the time being given that it's used on the other OpenFaaS community codebases. This is a great example though, I'll look back on it when I need Actions + Go.

**Comment by thomaspeitz** [comment]
<3 No worries

**Pull request closed without merging**
