### PR TITLE
Add blog post to README.md

### PR DESCRIPTION
**Pull request by JMacalinao**
Signed-off-by: JJ Macalinao <i@jmac.ph>

## Description

Added my blog post of creating a (hopefully up-to-date) Kubernetes cluster using k3sup, as requested by @openfaas.

## Motivation and Context

Creating HA cluster using both methods (embedded etcd and external DB), with notes relevant to Rancher and Longhorn installations as well.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by alexellis — APPROVED** [review]
Lgtm. Thank you

**Comment by alexellis** [comment]
It seems like the PR can't be merged without a rebase. You could do that it open a new PR if it's easier.

**Comment by JMacalinao** [comment]
@alexellis Rebase done. :)

**Comment by alexellis** [comment]
Awesome, thank you very much.

As a fan of k3sup please do consider becoming a GitHub Sponsor so I can continue this work, even on the lowest tier, it all helps.

**Pull request merged**
