### PR TITLE
Add Kubernetes-dashboard app and instructions

### LINKED ISSUE #125: [App request] Add kubernetes-dashboard
I have been trying to install kubernetes-dashboard and it hasn't been an easy task. Since it is very useful especially in testing / sandbox environments.

I would like to be able make it accessible via http and without password and with all permssions on the cluster. Keep in mind that I am talking about development clusters and not production ones for this. 

Useful links:
https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/
https://github.com/kubernetes/dashboard

Using the yml files provided in those official sources I have not been able to successfully deploy and operate the dashboard. I got the token and used it but it didn't redirect to the UI, it was stuck at the login screen.

### PR DESCRIPTION
**Pull request by Waterdrips**
This adds the kubernetes-dashboard to the app

closes #125

Signed-off-by: Alistair Hey <alistair@heyal.co.uk>

## Motivation and Context

- [x] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))
#125 

## How Has This Been Tested?

Installed on an x86 k3d cluster (clean cluster will nothing else installed)
The supported arches are: 
Screenshot 2019-12-11 at 14 44 45

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by Waterdrips** [comment]
These are the supported platforms:
Screenshot 2019-12-11 at 14 44 45

**Comment by alexellis** [comment]
This is a good excuse for you to buy an RPi4 :-)

**Comment by alexellis** [comment]
What's the pros / cons on using YAML vs helm?

https://github.com/helm/charts/tree/master/stable/kubernetes-dashboard

**Comment by alexellis** [comment]
This is how I accessed the dashboard including the password (token) https://blog.alexellis.io/kubernetes-in-10-minutes/

**Comment by Waterdrips** [comment]
> What's the pros / cons on using YAML vs helm?
> 
> https://github.com/helm/charts/tree/master/stable/kubernetes-dashboard

This was the approach in the kubernetes docs: https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/

**Comment by Waterdrips** [comment]
> This is how I accessed the dashboard including the password (token) https://blog.alexellis.io/kubernetes-in-10-minutes/

This same approach was used, (the raw yaml rather than whart) in your blog

**Comment by alexellis** [comment]
OK, thanks 👍

**Comment by alexellis** [comment]
How about the command I had for finding the secret, is it any better or worse?

**Comment by Waterdrips** [comment]
> How about the command I had for finding the secret, is it any better or worse?

The same as in the blog post (and the k8s docs) 💪

**Pull request merged**
