### PR TITLE
Add uninstall sub-command.

### PR DESCRIPTION
**Pull request by yankeexe**
Uninstall sub-command for  server and agent.

Signed-off-by: yankeexe <yankee.exe@gmail.com>

## Todo 
 - [ ] Add `--host` flag support.

## Description

Added Uninstall sub-command to run the uninstallation script for both server and agent. 
For server: has additional `--server` flag.

```bash 
$ k3sup uninstall --ip <ip> --user <user> --server
```

For agent: 

```bash 
$ k3sup uninstall --ip <ip> --user <user> 
```

**Need to discuss:** 
1. how to go forward uninstalling k3s and deleting agent nodes when master k3s is uninstalled from the master node.
2. Deleting node once k3s has been uninstalled from the agent node. (show uninstall instruction or k3sup does it for you?)

## **Update** 
Based on the questions I have asked [here](https://www.youtube.com/watch?v=k58WnbKmjdA), yanking k3s from the node is a manual process and the user has to go through each node to delete k3s from it.

Apart from the uninstall script, it is recommended to delete, `/var/lib/rancher/k3s` to start from a clean slate.

## Motivation and Context

- [x] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))
Easy uninstall k3s from command line without having to ssh into server and do it manually.

## How Has This Been Tested?

1. create 2 multipass instances. 
2. install master in one, and agent on the next. 
3. run `uninstall` sub command against both the nodes. 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by yankeexe** [comment]
@alexellis Can you please take a look at it?

**Comment by alexellis** [comment]
Hi @yankeexe thanks for this PR

Why is the `--server` flag required?

**Comment by alexellis** [comment]
Please could you add the new --host flag as per #290 ?

**Comment by alexellis** [comment]
@yankeexe when you have time, please could you take a look? Or let us know if you need someone else to take over.

**Comment by yankeexe** [comment]
Hey @alexellis  sorry for the delay. I am looking into it during the weekends.

**Comment by amalkh5** [comment]
@alexellis I will close this PR since  @yankeexe opened PR and is already up to date and remove from the server and the agent.

**Comment by parsec** [comment]
Does this need some attention to help it get pushed through? Came upon this while looking for tools to facilitate quick buildup/teardown of k3s.

**Comment by ncecere** [comment]
What is the status of this getting merged.  just wanted to check

**Comment by reesericci** [comment]
Any update on this? It's been more than a year since the last comment.

**Comment by alexellis** [comment]
Hi there. I think that gap shows that this feature may not be necessary. 

What's your usecase for uninstalling k3s? Explain to me in a few words why you feel you need that in k3sup. Thanks.

**Comment by reesericci** [comment]
One example that prompted me to make that comment was that I forgot to disable the servicelb/traefik and needed to rebuild the cluster with those config changes. Another example could be that someone chose the wrong k3s version and needed to rebuild the cluster.

Hopefully this answers your question!

--reese

**Pull request closed without merging**
